Add support for DUMP and RESTORE commands.
jamesls/fakeredis pull request #285
Opened 2020-11-18 03:34 UTC by charettes

One caveat is that they don't use the RDB format but pickle seemed like a good candidate to mimic what is expected to be an opaque and non-standard format.

2020-11-18 05:56 UTC, bmerry commented
Thanks. I'm going to have to think about this for a bit. In my use of fakeredis at work we have actually implemented DUMP with the redis format, but only for a few types (string, hash and zset). You can see it [here](https://github.com/ska-sa/katsdptelstate/blob/57c3c57c83282f315e1d1ea445829ebab0af947a/katsdptelstate/rdb_utility.py). The rdbtools package contains all the code for decoding the redis dump format, as well as documentation of it. So it would be nice to implement a DUMP that uses the redis format, but it would still require a lot more work, and maybe it's worth getting something going in the meantime.

I also try to avoid pickle where possible just because of the security implications (loading a pickle can execute arbitrary code). That's probably not such an issue for a unit testing library, but maybe something like msgpack would work just as well?

2020-11-18 12:29 UTC, charettes commented
> So it would be nice to implement a DUMP that uses the redis format, but it would still require a lot more work, and maybe it's worth getting something going in the meantime.

That's my general feeling as well. It makes sense to use RDB if that's the actual data storage of your _server_ but otherwise it feels like there's too much extra work involved for the sake of achieving this property

 It also brings the question of which version of RDB should be used, what if it changes between Redis versions? Do do you now support both format? Require a version flag to be specified on client creation?

> I also try to avoid pickle where possible just because of the security implications (loading a pickle can execute arbitrary code). That's probably not such an issue for a unit testing library, but maybe something like msgpack would work just as well?

I also think this isn't an issue for a library that advertise itself as having a single purpose: *to write unittests*. I guess other formats could work as well (e.g. base64 encoded `json.dump`) but `pickle` had the advantage of preserving the original Python type without requiring any form of massaging on serde (e.g. handling of byte strings, sets, dicts).

2020-11-18 14:52 UTC, bmerry commented
> I also think this isn't an issue for a library that advertise itself as having a single purpose: to write unittests.

Just because one builds a tool for a purpose doesn't mean people won't find other uses for it (e.g. #221) :smile: But I think it probably falls into the category of "good enough for now". I'm a little swamped at the moment, but I'll try to look at this in the next week - it does look like a nice small change.

2020-11-19 09:36 UTC, bmerry commented
I've decided I'm happy with the pickle approach for now. The code you've written so far looks good, but there are a few gaps in the implementation, and a few changes I'd like:
- In the README (where you've mentioned that pickle is used), can you add a warning about security e.g. "**Warning**: Do not use RESTORE with untrusted data, as a malicious pickle can execute arbitrary code."
- There should be a test of RESTORE with a non-zero TTL. Without freezegun it's probably not practical to check that the TTL was restored precisely, but a test that some TTL was restored would be good, maybe along with a very rough bounds check to catch any units mixup between ms and seconds.
- The RESTORE command returns an error if the target key already exists - that needs to be implemented and tested.
- There are several optional parameters to RESTORE. I think at a minimum REPLACE should be supported, and ABSTIME should be easy enough to support too. The others aren't really useful with fakeredis, but if it's not too difficult it wouldn't hurt to accept but ignore them.

2020-11-22 00:38 UTC, charettes commented
@bmerry thanks for the quick feedback.

All of above points were addressed except for support for `ABSTTL` and noop `IDLETIME` and `FREQ` as `redis-py` doesn't support these options yet as I assume they are quite niche

https://github.com/andymccurdy/redis-py/blob/8c176cdc7f36e2cbcd3254768766035a7b7cd8b3/redis/client.py#L1814-L1822

I have a commit ready for `ABSTTL` though assuming `redis-py` catches up which I'll submit as another PR based on this one. The test it include fails with a `TypeError` though for the reasons explained above but I guess work could be reused if support for `absttl=True` ever lands upstream.

2020-11-22 08:07 UTC, bmerry requested changes
Thanks for the work. Just a few more niggles I missed the first time.

2020-11-22 08:07 UTC, bmerry commented on fakeredis/_server.py
> +    @command((Key(),))
I think you need the following to make this do the right thing if the key doesn't exist (which also needs a test):
```suggestion
    @command((Key(missing_return=None),))
```

2020-11-22 22:54 UTC, charettes commented on fakeredis/_server.py
> +            if casematch(args[i], b'replace') and not replace:
Ah TIL

2020-11-22 23:03 UTC, charettes commented on fakeredis/_server.py
> +            raise redis.ResponseError(RESTORE_KEY_EXISTS)
I don't think so, here's what you get using `redis-py` against an existing Redis server.

![](https://cdn.zappy.app/9fe67027c2e93d5b1ef5d78ade22376e.png)

![](https://cdn.zappy.app/36433bdef271788d17e0653f86996d73.png)

![](https://cdn.zappy.app/e9f0e546ca03f63f8a95370c9ca94bfb.png)

2020-11-22 23:06 UTC, charettes commented on fakeredis/_server.py
> +            raise redis.ResponseError(RESTORE_KEY_EXISTS)
Ahh looks like `SimpleError` are turned into `ResponseError` automatically.

2020-11-22 23:07 UTC, charettes commented on fakeredis/_server.py
> +    # Generic commands
Any thoughts about adjusting the `README` to match the Redis command reference? That's where I got the order from.

2020-11-22 23:14 UTC, charettes commented
@bmerry all comments should be addressed.

2020-11-23 06:27 UTC, bmerry commented on fakeredis/_server.py
> +            raise redis.ResponseError(RESTORE_KEY_EXISTS)
Indeed. fakeredis also support aioredis, where SimpleError gets turned into an aioredis exception.

2020-11-23 06:31 UTC, bmerry commented on fakeredis/_server.py
> +    # Generic commands
I think what's happened is that the data that backs the command reference has two names for each section e.g. the URL for the "Keys" section is https://redis.io/commands#generic. The script that generates that section of the README is using the short names (hence "generic") but the comments in `_server.py` use the long names.

2020-11-23 06:32 UTC, bmerry commented
Thanks for the work - all looks good now!

2020-11-23 06:32 UTC, bmerry approved these changes

2020-11-23 06:32 UTC, merged

2020-11-23 14:45 UTC, charettes commented
Thanks for the merge @bmerry. Any idea when a new release containing these changes will be released? We're currently using a monkeypatch of `FakeServer` we'd like to eventually get rid of.

2020-11-23 18:16 UTC, bmerry commented
> Any idea when a new release containing these changes will be released?

There's one PR in progress which I hope to get merged this week before a release. I just have to remember to make time in my day job. If you haven't seen anything by next Thursday then feel free to remind me again.

2020-11-25 19:11 UTC, charettes commented
Thanks for the release @bmerry, appreciate 🙇